import "pkg:/components/stores/stores.bs"
import "pkg:/components/http/http.bs"
import "pkg:/components/utils/RouterUtils.bs"

function Show(args)
    setRouter(m.top.ComponentController)
    stores.init()
    http.init()

    if stores.tokenStore().fabricToken = ""
        router()@.show({ view: CreateObject("roSGNode", "Home") })
    else
        router()@.show({ view: CreateObject("roSGNode", "Dashboard") })
    end if

    m.top.signalBeacon("AppLaunchComplete")
end function
